### ISSUE TITLE
[Bug] Errors on starting

### ISSUE THREAD

**Issue by CapekM** [jrbudda/Vivecraft_113#11]
Hi,

I'm using windows MR and when i started your application i got some warnings and tons of errors ending in crash of Steam VR.
![error_log](https://user-images.githubusercontent.com/46975680/54068463-45a70700-424d-11e9-88cf-e8ecd1e5c870.png)
![warnings](https://user-images.githubusercontent.com/46975680/54068489-8272fe00-424d-11e9-9f9a-261b4603eedf.PNG)

I tried to reinstall graphics driver.
If you have any suggestions they are welcome!

**Comment by TheTrueForce** [comment]
You should probably pastebin the text of the logs and post the link here. That way whoever ends up handling this can actually go through them.

**Comment by TheTrueForce** [comment]
Actually... Are you on a laptop? A really common problem for laptops with optimus graphics is that Vivecraft runs on the wrong GPU. Check http://www.vivecraft.org/faq/, and check the section titled "The game shows up on my desktop, but not in the headset!"

**Comment by CapekM** [comment]
Looks like my problem. Thanks

**Comment by CapekM** [comment]
I'm on laptop and i have this problem "The game shows up on my desktop, but not in the headset!".
I set high-performance NVIDIA but still got the errors.
[latest.log](https://github.com/jrbudda/Vivecraft_113/files/2948264/latest.log)

**Comment by Techjar** [comment]
You didn't set it properly, you're still using the Intel GPU. I'm guessing you probably set it for Minecraft.exe, which won't work, as that's just the launcher. You need to set it globally (or for java.exe and javaw.exe, but this is not straightforward so setting it globally is just easier).

**Comment by CapekM** [comment]
You're right. Thanks :)
