### ISSUE TITLE
Transparent In-Game menus

### ISSUE THREAD

**Issue by retr0virus** [jrbudda/Vivecraft_113#13]
Hello,
it seems that Vivecraft now is working with AMD Vega GPUs under Linux. :-)
What was strange is that the buttons are all unmapped so I was only able to open the game menu but nothing else before mapping the buttons in the menu. 
What I then noticed was that it was nearly impossible to select anything while not returning to the main menu because the ingame menu and also the inventory was totally unreadable. Even with a solid background.
I later noticed that it is because of the transparency of the menu. So instead of being opaque I was able to see trough the menu and inventory - what makes it completely unreadable in nearly all situations. I already set the hud to completely opaque (1.0) and enabled the background for the the menu but this didn't help (the area around the inventory/menu is black the transparency on the menu itself still remains).
Is there another possibility to make the menu and inventory "solid" - at least when you toggle on the solid background for the menu?
What I also noticed is that I can also see through everything I hold in my hands - like sand blocks or so. I then for example see everything brown through the block but still I am able to see the landscape.
This doesn't disturb me but maybe this is also related to the "transparency bug".

**Comment by Techjar** [comment]
We're not too keen on trying to work around shitty driver bugs.

**Comment by Techjar** [comment]
We're not too keen on trying to work around shitty driver bugs, if that's what's going on here. Though your whole description is a bit confusing. Could you provide screenshots?

**Comment by retr0virus** [comment]
I am running Arch Linux with kernel 5.0.5.arch1-1, mesa 19.0.1-2, vulkan-radeon 19.0.1-2. I have a AMD Radeon RX Vega 64.
I attached some "screenshots" (had to take photos with my smartphone as the ingame screenshots doesn't work in menus). It looks worse on the Vive but I think you can see the issue.

![mcvr_002](https://user-images.githubusercontent.com/137628/55683007-039bde80-593b-11e9-99b6-67ee45fa49d8.jpg)
![mcvr_003](https://user-images.githubusercontent.com/137628/55683009-0565a200-593b-11e9-9cdd-73016b9a058d.jpg)
![mcvr_004](https://user-images.githubusercontent.com/137628/55683010-0696cf00-593b-11e9-845b-8c8fcbd7515f.jpg)
![mcvr_005](https://user-images.githubusercontent.com/137628/55683011-08609280-593b-11e9-83fe-6525368d0db8.jpg)
![mcvr_006](https://user-images.githubusercontent.com/137628/55683012-0a2a5600-593b-11e9-8795-5e0a243d277d.jpg)
![mcvr_007](https://user-images.githubusercontent.com/137628/55683013-0bf41980-593b-11e9-90d3-459636478313.jpg)
![mcvr_008](https://user-images.githubusercontent.com/137628/55683015-0dbddd00-593b-11e9-940a-2168ab7d57fb.jpg)
![mcvr_009](https://user-images.githubusercontent.com/137628/55683016-0f87a080-593b-11e9-9d1a-2e050fe50d45.jpg)

**Comment by jrbudda** [comment]
this should be better in newer versions of 1.13 with shaders on
