### ISSUE TITLE
BDCraft Sword, Torch mis-scaled, improperly rotated

### ISSUE THREAD

**Issue by Romaq** [jrbudda/Vivecraft_113#14]
I'm using BDCraft 128^2. Everything appears to work properly using OptiFine 1.13.2 HD U E8 pre1 (no ViveCraft), AND ViveCraft works fine using Vanilla textures. I suspect the bug is actually with BDCraft, but since it works correctly using Optifine, I need to know what to report to BDCraft so they can fix the scale and rotation of the torch, the bow, and anything else lacking the correct mapping info.

**Comment by jrbudda** [comment]
There are no 'vr' mappings. Any model rotations in the resource pack are thrown out, and vivecraft does its best to place items in the correct orientation. The way minecraft makes item models is by turning the 2d image into a 3d model. If the 2d image is rotated differently than the vanilla image, the model is rotated. We have no way to detect that. You pretty much have to live with it or use a different resource pack.

**Comment by Romaq** [comment]
Thank you. I can live with it. :)
