### ISSUE TITLE
[Bug] 1.13 New vanilla swimming mechanic uses wrong viewpoint position

### ISSUE THREAD

**Issue by steven-archer** [jrbudda/Vivecraft_113#16]
With the aquatic update comes a new swimming mechanic. Sprinting while swimming will put the player prone in the water, and also changes their hitbox height, allowing them to swim through a 1x1 block tunnel.

Bug: Vivecraft does not lower the perspective to the player's new head position while swimming prone, resulting in the viewpoint clipping up through blocks if the player swims under them. This causes the view to go completely black, as if you were sticking your head through a solid block wall.

Fix: The vanilla game lowers the perspective of the player while swimming to match the position of their head when prone in the water. In Vivecraft, the viewpoint should also be lowered as such.

**Comment by jrbudda** [comment]
Vivecraft also does not move the players head when sneaking or entering a vehicle. This is intended for motion sickness purposes.

**Comment by steven-archer** [comment]
That is understandable. However, it does break part of the vanilla swimming mechanic. Without some kind of workaround, vivecraft currently barrs the usage of vanilla swimming, and I'd argue that having your view go completely black when trying to navigate a shipwreck, a guardian temple, or an underwater cave is far more disorienting than moving the viewpoint slightly. Bedrock VR managed to pull it off by doing a smooth transition downwards and back up. Maybe a similar or alternate approach could be implemented as an option to restore full use of the vanilla swimming mechanic.

**Comment by jrbudda** [comment]
You could duck

**Comment by polyjitter** [comment]
I absolutely do not understand the purpose of breaking a basic mechanic and refusing to add any option to make it work when you already provide smooth locomotion.

**Comment by steven-archer** [comment]
I'm not here for drama, I'm just here pointing out something that is broken. 

As far as ducking goes, I doubt you'll find many people willing to crouch down to near half their height. I'm 6 feet, so that places my Minecraft sightline in at least 1.5 blocks height. That would mean that in order to see while trapped underwater, I would have to lower my actual head to below 3½ feet, which would be quite strenuous to hold for long periods of time and a bit impractical. Holding a mega-squat for the whole duration of an underwater temple boss would be God-tier, and I'm no atlas-man :P While it would be a good workout for the legs and core muscles, the fingers tend to lose dexterity under that sort of strain, so controlling the joysticks with any kind of precision would become a pain, literally. 

In any case, if fixing an incompatibility with vanilla features is not open to discussion, you may want to close this report as "unsolvable" from a technical perspective.

**Comment by Techjar** [comment]
Have you tried laying on your stomach? That is much more like a swimming position.

There's no real way to solve this unfortunately. We'd have to spontaneously offset the room origin to compensate for the reduced height, which is something we are adamantly against doing. It's not the same as other actions that move you around, as those are triggered intentionally, while this just happens suddenly while swimming.

**Comment by steven-archer** [comment]
The action is very intentional, and requires you to press sprint while moving underwater. Not doing both of those will not trigger the new swimming mechanic. To stop swimming you release the movement joystick/buttons. This is how it works in unmodded vanilla.

You could examine for yourself how it actually works by loading into a completely vanilla game without mods. I'll see if I can find a video clip demonstrating how the official Minecraft VR on Bedrock Edition pulls it off without it being too jarring. It might help to see it in action.

**Comment by steven-archer** [comment]
I couldn't find any footage readily available. So I captured it myself and I had my youtube friend put together and upload it to his channel. Hopefully its a little easier to see the need to fix this. The video explains the bug and shows how the Mojang devs implemented it in their VR version.

https://youtu.be/ClM9onE839Q
[![ViveCraft Aquatic Update Swimming Bug](https://img.youtube.com/vi/ClM9onE839Q/0.jpg)](https://www.youtube.com/watch?v=ClM9onE839Q)

**Comment by impmallet** [comment]
Hello, I operate a VR compatible server and my players have also complained of this. I see the validity of both perspectives, but steve does make some compelling points. Would it be technically feasible to implement a toggle option for players who wish to have this vanilla mechanic enabled?

**Comment by jrbudda** [comment]
Bedrock VR does not have roomscale swimming, If you roomscale swim fast enough, it triggers swim sprint and turns it off if you slow down. This makes it possible to very quickly switch in and out of swim-sprint without intention which would be very unpleasant if artificial room offsets are applied, whether instant or interpolated. 

The ideal solution would be to move the hitbox 'up' instead of the view down, so its centered on your upper body and making the transition seamless. This would require moving the actual player location up since you cant modify hitboxes only on the client. I do not know how feasible that is, the distance should be short enough to bypass anti-cheat but I'm not 100%. We also have no framework in place to make that kind of offset to the player position and theres a ton of potential for view jumping depending on how the position change gets handled and returned from the server. I will look into this as a way forward.
