### ISSUE TITLE
Can't see my friends movement

### ISSUE THREAD

**Issue by MimbleDimble** [jrbudda/Vivecraft_113#17]
I recently downloaded Vivecraft with my friend and we played together, but i couldn't see his arm and head movement, and it kind of removed a little bit of the feeling of being in VR minecraft with my friend. Is there anything i can do to fix this?

**Comment by Espergium** [comment]
http://www.vivecraft.org/faq/

**Comment by FonceTheDemon** [comment]
Your friend must install vivecraft NON-VR to see your movements

![Capture d’écran (6)_LI](https://user-images.githubusercontent.com/93097737/138610677-faec0a9c-3fa1-428f-8e85-d9dff23ac683.jpg)
