### ISSUE TITLE
Camera spinning

### ISSUE THREAD

**Issue by SilencedSoppu** [jrbudda/Vivecraft_113#18]
I went from the 1.12.2 client to the 1.13.2 client. Now the camera spins while i am minding my own business, steam VR shows no issues or errors. I simple remedy is flicking my left analog stick side to side but that only works for a couple minutes before it goes back to spinning again.

**Comment by Techjar** [comment]
Increase the deadzone in the freemove settings.

**Comment by jrbudda** [comment]
This should be fixed in v8, assuming you have a Rift or WMR.
