### ISSUE TITLE
1.14?

### ISSUE THREAD

**Issue by oldaccount123434** [jrbudda/Vivecraft_113#20]
Hey! I was wondering if there will ever be a 1.14 version of vivecraft or if there is one in the making already then if you could tell me an eta on when that would be finished it would be great!

**Comment by Techjar** [comment]
We have decided not to support 1.14 or any future versions.
 
 
 
 
 
 
 
I am of course kidding, but please have patience, we are waiting on MCP and OptiFine to update. Not to mention 1.14 is apparently a mess right now and Mojang themselves are even recommending that people not use it.

**Comment by oldaccount123434** [comment]
Yeah, me and my friends started doing a play through on it and I had just wanted to see when or if you had planned on making one... I appreciate the quick response as usually I have to wait til the next day lol. I have noticed many weird chunk glitched where its almost like x-ray "hacks".

**Comment by jrbudda** [comment]
done
