### ISSUE TITLE
Valve Index Controller Support

### ISSUE THREAD

**Issue by StefanJanssen95** [jrbudda/Vivecraft_113#22]
So everyone who has set foot in the VR space must have heard of the new Index Controllers (previously called Knuckles). I was wondering if ViveCraft is going to get support for them.

They support full finger tracking and letting go of the controller completely while staying attached to your hand. Now I know you don't have fingers in minecraft. But I do see some possibilities there.

**Comment by Techjar** [comment]
Already on the todo list, waiting on my Index controllers. Will probably be able to start work sometime around late July to early August, depending on exactly when stock is available.

**Comment by Techjar** [comment]
I should clarify, as you might expect, we won't be doing visual fingers as that's just going to look weird in Minecraft (and is really hard to render in the "engine"). That said, I have been thinking of ways we could use the finger tracking for roomscale interactions, but don't have anything concrete yet.

Initial support will simply be setting up a sensible button configuration for the controllers, as none of the existing controller layouts suit the particular design of the controllers. Once that's done, we can worry about how to handle finger tracking data.

**Comment by StefanJanssen95** [comment]
I understand difficulties may arise for it. I did think of some ideas but backporting it to other controllers are not possible

**Comment by jrbudda** [comment]
this is done
