### ISSUE TITLE
Third vive Tracker/Controller camera settings reset after restart Vivecraft

### ISSUE THREAD

**Issue by BetmanSmall** [jrbudda/Vivecraft_113#25]
Hello, thank for your work. Minecraft in VR is awesome.

I try configurate Mixed Reality. I mounted the tracker over the camera. Configurated virtual camera in Minecraft by dint of hotkeys: offsets, rotations, rolls. It work normal. But after exit from VIveCraft. And restarted him. That settingin reset. And I have to set up it again. It is not good. lost my time again.
I check optionsviveprofiles.txt and in this file I see the camera settings. But after restart they are reset. I tried to copy and paste them after launch. Tried set read-only flag on this file. Without success.

Help me pliz. Sorry for my english.

<details><summary>CLICK ME</summary>
<p>

![fjbB8ZbSpZg](https://user-images.githubusercontent.com/5994526/59466924-1f3dcc80-8e37-11e9-9062-127a80bc3060.jpg)

</p>
</details>

**Comment by Techjar** [comment]
There's a typo in one of the quaternion components, will fix this soon.

**Comment by Techjar** [comment]
To be clear, only the rotation Y component should be reset, which totally messes up the quaternion. The position offset should not be affected. Is this the behavior you experience?

**Comment by BetmanSmall** [comment]
I'll check it out tomorrow. But it seems to me that all settings have been reset. because I had to shift it all the same not only to rotate

**Comment by Techjar** [comment]
Ah, the nonsense quaternion caused by the reset Y component messes up the whole thing, since they are both applied in the transform in a specific way. Once we fix the bug, you should reset all the rotation offset values by deleting the lines from the file (there's 4), otherwise things are going to act weird.

**Comment by BetmanSmall** [comment]
Okay, we'll wait, thx

**Comment by jrbudda** [comment]
[vivecraft-1.13.2-jrbudda-2-b5-installer.exe.zip](https://github.com/jrbudda/Vivecraft_113/files/3288172/vivecraft-1.13.2-jrbudda-2-b5-installer.exe.zip)

**Comment by BetmanSmall** [comment]
it is work. thx
