### ISSUE TITLE
[Implement&Fix] ShowHands not work in MixedReality and something

### ISSUE THREAD

**Issue by BetmanSmall** [jrbudda/Vivecraft_113#26]
Hi guys! It's me again.

I'm still trying to set up mixed reality. And I noticed that the hands stopped working with the latest beta updates. What is the fun thing on the menu, they work, but the game does not. Video is attached.

And also, may I ask you to implement the option to hide the player’s avatar and hands in the mode of the Third Person. Because I do not want to use 4K resolution to record only one of the four squares of full HD. It will be enough for me to have full third-party camera resolution.

Oh yeah and still, teleport broke. Well, it seems to work, but without an arc and not for such far distances as we would like. Free motion works fine.

Configs and video attach. Use b9

[options.txt](https://drive.google.com/open?id=1hmwsbHZnrQo04vlXmsmSuy3sEz4_9t0S)
[optionsviveprofiles.txt](https://drive.google.com/open?id=1McbECWhjEn6eUDtuio6KsK9Q449PSLR4)
[vivecraftTest1.mp4](https://drive.google.com/open?id=1WH4LPXxTbvyrx2bxDnDANzAYouH_VEYP)

**Comment by jrbudda** [comment]
Should be fixed in release version of v2
